"""
Generated by ArcGIS ModelBuilder on : 2021-11-10 11:23:51
"""
import arcpy
from sys import argv

def CadShapefile(Input_Features, Output_Folder, Output_Name, Extent="DEFAULT", Output_Coordinate_System):  # Eos GPS to Shapefile

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"H:\GIS\Working\Marks\CadShapefileTool\Default.gdb", workspace=r"H:\GIS\Working\Marks\CadShapefileTool\Default.gdb"):

        # Process: Feature Class To Feature Class (Feature Class To Feature Class) (conversion)
        with arcpy.EnvManager(extent=Extent, outputCoordinateSystem=Output_Coordinate_System):
            Output_Shapefile = arcpy.conversion.FeatureClassToFeatureClass(in_features=Input_Features, out_path=Output_Folder, out_name=Output_Name, where_clause="", field_mapping="", config_keyword="")[0]

        # Process: Add Elevation_ft Field (Add Field) (management)
        with arcpy.EnvManager(workspace=r"C:\Users\mmarks\AppData\Local\Temp\ArcGISProTemp15836\42b85dce-9c9a-4ca1-bc2d-a4f18d6f7336\Default.gdb"):
            Updated_Shapefile = arcpy.management.AddField(in_table=Output_Shapefile, field_name="Elev_ft", field_type="DOUBLE", field_precision=None, field_scale=None, field_length=None, field_alias="Elevation (ft)", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

        # Process: Add XY Coordinates (Add XY Coordinates) (management)
        Updated_Input_Features = arcpy.management.AddXY(in_features=Updated_Shapefile)[0]

        # Process: Calculate Field (Calculate Field) (management)
        TreesAOI_shp = arcpy.management.CalculateField(in_table=Updated_Input_Features, field="Elev_ft", expression="!POINT_Z! * 3.2808", expression_type="PYTHON3", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

        # Process: Adjust 3D Z (Adjust 3D Z) (management)
        Updated_Features = arcpy.management.Adjust3DZ(in_features=TreesAOI_shp, reverse_sign="NO_REVERSE", adjust_value=0, from_units="METERS", to_units="FEET")[0]

        # Process: Add XY Coordinates (2) (Add XY Coordinates) (management)
        Updated_Input_Features_2_ = arcpy.management.AddXY(in_features=Updated_Features)[0]

if __name__ == '__main__':
    CadShapefile(*argv[1:])
